runtime: python311


entrypoint: GOOGLE_APPLICATION_CREDENTIALS=secrets/google-credentials.json NLTK_DATA=gaedata gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app --timeout 60 --workers 1 --threads 6
default_expiration: "300d 5h"

handlers:

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json
- url: /sitemap_index.xml
  static_files: static/sitemap_index.xml
  upload: static/sitemap_index.xml
  http_headers:
    Content-Type: text/xml
# favicon
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  http_headers:
    Vary: Accept-Encoding
    Cache-Control: public, max-age=604800, immutable
- url: /.well-known/apple-developer-merchantid-domain-association
  static_files: static/apple-developer-merchantid-domain-association
  upload: static/apple-developer-merchantid-domain-association
  http_headers:
    Vary: Accept-Encoding
    Cache-Control: public, max-age=604800, immutable
- url: .*
  script: main.app

instance_class: F1
#yolo/slow autoscailing
automatic_scaling:
  min_pending_latency: 5s # 5 is the min
  max_pending_latency: 15s # 15 is the max
  target_cpu_utilization: 0.9 # save cost by not having too many instances
  max_concurrent_requests: 50 # 50 is high but dont want to scale so aggressively to avoid cost
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s


inbound_services:
- warmup
